import { jsPDF } from "jspdf";

export function downloadRecipePDF(recipe) {
  const doc = new jsPDF();

  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const maxWidth = 170;

  let y = 20;

  function addLine(text = "", size = 12, gap = 8) {
    doc.setFontSize(size);

    const lines = doc.splitTextToSize(text, maxWidth);

    if (y + lines.length * gap > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }

    doc.text(lines, margin, y);

    y += lines.length * gap;
  }

  // Title
  addLine(recipe.title || "Recipe", 22, 10);

  y += 5;

  // Description
  addLine(`Description: ${recipe.description || ""}`);

  y += 5;

  addLine(`Cooking Time: ${recipe.cookingTime || "-"}`);
  addLine(`Difficulty: ${recipe.difficulty || "-"}`);
  addLine(`Servings: ${recipe.servings || "-"}`);
  addLine(`Calories: ${recipe.calories || "-"}`);

  y += 5;

  // Ingredients
  addLine("Ingredients", 18, 9);

  (recipe.ingredients || []).forEach((item) => {
    const ingredient =
      typeof item === "string"
        ? item
        : `${item.quantity || ""} ${item.item || ""}`;

    addLine(`• ${ingredient}`);
  });

  y += 5;

  // Steps
  addLine("Cooking Steps", 18, 9);

  (recipe.steps || []).forEach((step, index) => {
    addLine(`${index + 1}. ${step}`);
  });

  y += 5;

  // Nutrition
  addLine("Nutrition", 18, 9);

  addLine(`Calories: ${recipe.calories || "-"}`);
  addLine(`Protein: ${recipe.nutrition?.protein || "-"}`);
  addLine(`Carbs: ${recipe.nutrition?.carbs || "-"}`);
  addLine(`Fat: ${recipe.nutrition?.fat || "-"}`);

  y += 5;

  // Chef Tip
  addLine("Chef Tip", 18, 9);
  addLine(recipe.tips || "No tips available.");

  y += 5;

  // Footer
  doc.setFontSize(10);
  doc.text(
    "Generated by ChefNova AI - Sharan Kumusagi",
    margin,
    pageHeight - 10
  );

  doc.save(`${recipe.title || "Recipe"}.pdf`);
}